In [32]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [2]:
Data = pd.read_csv("Insurance_Marketing-Customer-Value-Analysis (1).csv").values

In [3]:
print(Data.shape)

(9134, 24)


In [6]:
print(Data[0:2,:])

[['BU79786' 'Washington' 2763.519279 'No' 'Basic' 'Bachelor' '2/24/2011'
  'Employed' 'F' 56274 'Suburban' 'Married' 69 32 5 0 1 'Corporate Auto'
  'Corporate L3' 'Offer1' 'Agent' 384.811147 'Two-Door Car' 'Medsize']
 ['QZ44356' 'Arizona' 6979.535903 'No' 'Extended' 'Bachelor' '1/31/2011'
  'Unemployed' 'F' 0 'Suburban' 'Single' 94 13 42 0 8 'Personal Auto'
  'Personal L3' 'Offer3' 'Agent' 1131.464935 'Four-Door Car' 'Medsize']]


In [11]:
X = np.concatenate((Data[:,0:2],Data[:,3:]),axis = 1)
Y = Data[:,2]

In [12]:
print(X[0])

['BU79786' 'Washington' 'No' 'Basic' 'Bachelor' '2/24/2011' 'Employed' 'F'
 56274 'Suburban' 'Married' 69 32 5 0 1 'Corporate Auto' 'Corporate L3'
 'Offer1' 'Agent' 384.811147 'Two-Door Car' 'Medsize']


In [13]:
print(Y)

[2763.519279 6979.535903 12887.43165 ... 8163.890428 7524.442436
 2611.836866]


In [69]:
X_cat = X[:,[1,2,3,4,6,7,9,10,16,17,18,19,21,22]]
print(X_cat[:,0])
print(X_cat.shape)
print(len(X_cat))

['Washington' 'Arizona' 'Nevada' ... 'California' 'California'
 'California']
(9134, 14)
9134


In [114]:
enc1 = LabelEncoder()
X_cat_t = enc1.fit_transform(X_cat[:,0])
print(X_cat_t.shape)
for i in range(1,14):
    print(i)
    enc1 = LabelEncoder()
    X_cat_t = np.vstack((X_cat_t,enc1.fit_transform(X_cat[:,i])))
    print(enc1.classes_)

(9134,)
1
[0 1]
2
[0 1 2]
3
[0 1 2 3 4]
4
[0 1 2 3 4]
5
[0 1]
6
[0 1 2]
7
[0 1 2]
8
[0 1 2]
9
[0 1 2 3 4 5 6 7 8]
10
[0 1 2 3]
11
[0 1 2 3]
12
[0 1 2 3 4 5]
13
[0 1 2]


In [78]:
print(X_cat_t.shape)

(14, 9134)


In [93]:
print(X_cat_t[0:14,0:20])

[[4 0 2 1 4 3 3 0 3 3 1 1 1 0 1 3 2 1 3 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 2 0 0 0 0 2 0 1 0 0 2 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 1 4 0 1 1 1 4 3 1 0 3 1 1 3]
 [1 4 1 4 1 1 1 4 2 1 4 4 1 1 1 1 2 2 1 1]
 [0 0 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 1 0]
 [1 1 1 1 0 0 1 2 1 2 1 1 2 1 2 0 1 1 2 1]
 [1 2 1 1 2 1 1 2 0 1 2 1 1 1 2 1 1 1 1 1]
 [0 1 1 0 1 1 0 0 0 2 1 1 0 0 0 0 1 1 1 0]
 [2 5 5 1 3 5 2 2 2 7 5 5 0 2 2 1 5 4 4 1]
 [0 2 0 0 0 1 0 0 0 1 0 1 1 1 3 1 1 2 1 0]
 [0 0 0 2 0 3 0 0 0 1 0 0 0 1 2 1 2 2 1 2]
 [5 0 5 3 0 5 0 0 0 0 0 3 0 3 0 0 5 3 0 0]
 [1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2]]


In [94]:
X_cat = np.transpose(X_cat_t)
print(X_cat.shape)

(9134, 14)


In [96]:
enc = OneHotEncoder()
X_cat_one_hot = enc.fit_transform(X_cat)

In [120]:
print(X_cat_one_hot.shape)
print(np.sum(X_cat_one_hot[0]))
print(X_cat_one_hot[0,7])

(9134, 57)
14.0
1.0


In [119]:
np.savetxt("X_categorical.csv",X_cat_one_hot, delimiter = ",")

ValueError: Expected 1D or 2D array, got 0D array instead