In [202]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [149]:
Data = pd.read_csv("Insurance_Marketing-Customer-Value-Analysis (1).csv").values

In [150]:
print(Data.shape)

(9134, 24)


In [151]:
print(Data[0:2,:])

[['BU79786' 'Washington' 2763.519279 'No' 'Basic' 'Bachelor' '2/24/2011'
  'Employed' 'F' 56274 'Suburban' 'Married' 69 32 5 0 1 'Corporate Auto'
  'Corporate L3' 'Offer1' 'Agent' 384.811147 'Two-Door Car' 'Medsize']
 ['QZ44356' 'Arizona' 6979.535903 'No' 'Extended' 'Bachelor' '1/31/2011'
  'Unemployed' 'F' 0 'Suburban' 'Single' 94 13 42 0 8 'Personal Auto'
  'Personal L3' 'Offer3' 'Agent' 1131.464935 'Four-Door Car' 'Medsize']]


In [152]:
X = np.concatenate((Data[:,0:2],Data[:,3:]),axis = 1)
Y = Data[:,2]

In [153]:
print(X[0])

['BU79786' 'Washington' 'No' 'Basic' 'Bachelor' '2/24/2011' 'Employed' 'F'
 56274 'Suburban' 'Married' 69 32 5 0 1 'Corporate Auto' 'Corporate L3'
 'Offer1' 'Agent' 384.811147 'Two-Door Car' 'Medsize']


In [154]:
print(Y)

[2763.519279 6979.535903 12887.43165 ... 8163.890428 7524.442436
 2611.836866]


In [194]:
X_cat = X[:,[1,2,3,4,6,7,9,10,16,17,18,19,21,22]]
print(X_cat[:,0])
print(X_cat.shape)
print(len(X_cat))

['Washington' 'Arizona' 'Nevada' ... 'California' 'California'
 'California']
(9134, 14)
9134


In [195]:
enc1 = LabelEncoder()
X_cat_t = enc1.fit_transform(X_cat[:,0])
print(enc1.classes_)
print(X_cat_t.shape)
for i in range(1,14):
    print(i)
    enc1 = LabelEncoder()
    X_cat_t = np.vstack((X_cat_t,enc1.fit_transform(X_cat[:,i])))
    print(enc1.classes_)

['Arizona' 'California' 'Nevada' 'Oregon' 'Washington']
(9134,)
1
['No' 'Yes']
2
['Basic' 'Extended' 'Premium']
3
['Bachelor' 'College' 'Doctor' 'High School or Below' 'Master']
4
['Disabled' 'Employed' 'Medical Leave' 'Retired' 'Unemployed']
5
['F' 'M']
6
['Rural' 'Suburban' 'Urban']
7
['Divorced' 'Married' 'Single']
8
['Corporate Auto' 'Personal Auto' 'Special Auto']
9
['Corporate L1' 'Corporate L2' 'Corporate L3' 'Personal L1' 'Personal L2'
 'Personal L3' 'Special L1' 'Special L2' 'Special L3']
10
['Offer1' 'Offer2' 'Offer3' 'Offer4']
11
['Agent' 'Branch' 'Call Center' 'Web']
12
['Four-Door Car' 'Luxury Car' 'Luxury SUV' 'SUV' 'Sports Car'
 'Two-Door Car']
13
['Large' 'Medsize' 'Small']


In [157]:
print(X_cat_t.shape)

(14, 9134)


In [158]:
print(X_cat_t[0:14,0:20])

[[4 0 2 1 4 3 3 0 3 3 1 1 1 0 1 3 2 1 3 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 2 0 0 0 0 2 0 1 0 0 2 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 1 4 0 1 1 1 4 3 1 0 3 1 1 3]
 [1 4 1 4 1 1 1 4 2 1 4 4 1 1 1 1 2 2 1 1]
 [0 0 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 1 0]
 [1 1 1 1 0 0 1 2 1 2 1 1 2 1 2 0 1 1 2 1]
 [1 2 1 1 2 1 1 2 0 1 2 1 1 1 2 1 1 1 1 1]
 [0 1 1 0 1 1 0 0 0 2 1 1 0 0 0 0 1 1 1 0]
 [2 5 5 1 3 5 2 2 2 7 5 5 0 2 2 1 5 4 4 1]
 [0 2 0 0 0 1 0 0 0 1 0 1 1 1 3 1 1 2 1 0]
 [0 0 0 2 0 3 0 0 0 1 0 0 0 1 2 1 2 2 1 2]
 [5 0 5 3 0 5 0 0 0 0 0 3 0 3 0 0 5 3 0 0]
 [1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2]]


In [173]:
X_cat = np.transpose(X_cat_t)
print(X_cat.shape)
print(X_cat[0])

(9134, 14)
[4 0 0 0 1 0 1 1 0 2 0 0 5 1]


In [181]:
# enc = OneHotEncoder()
# X_cat_one_hot = enc.fit_transform(X_cat)
X_trial = np.array(pd.get_dummies(X_cat[0]))
print(type(X_trial))
print(X_trial[0])

<class 'numpy.ndarray'>
[0 0 0 1 0]


In [196]:
X_cat_one_hot = np.concatenate([np.array(pd.get_dummies(X_cat[:,0])),
                                np.array(pd.get_dummies(X_cat[:,1])),
                                np.array(pd.get_dummies(X_cat[:,2])),
                                np.array(pd.get_dummies(X_cat[:,3])),
                                np.array(pd.get_dummies(X_cat[:,4])),
                                np.array(pd.get_dummies(X_cat[:,5])),
                                np.array(pd.get_dummies(X_cat[:,6])),
                                np.array(pd.get_dummies(X_cat[:,7])),
                                np.array(pd.get_dummies(X_cat[:,8])),
                                np.array(pd.get_dummies(X_cat[:,9])),
                                np.array(pd.get_dummies(X_cat[:,10])),
                                np.array(pd.get_dummies(X_cat[:,11])),
                                np.array(pd.get_dummies(X_cat[:,12])),
                                np.array(pd.get_dummies(X_cat[:,13])),],axis = 1)

In [197]:
print(X_cat_one_hot.shape)
print(X_cat_one_hot[0])
#np.savetxt("X_categorical.csv",X_cat_one_hot, delimiter = ",")

(9134, 57)
[0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]


In [198]:
X_numerical = X[:,[8,11,12,13,14,15,20]]
print(X_numerical.shape)
print(X_cat_one_hot.shape)

(9134, 7)
(9134, 57)


In [199]:
X = np.concatenate((X_numerical,X_cat_one_hot),axis = 1)

In [201]:
print(X.shape)
print(Y.shape)

(9134, 64)
(9134,)


In [203]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [205]:
print(X_train.shape, X_test.shape)
print(Y_train.shape, Y_test.shape)

(6119, 64) (3015, 64)
(6119,) (3015,)
